// Mocks generated by Mockito 5.0.3 from annotations
// in movies_gallery/test/features/movies_grid/data/repositories/movies_repository_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:movies_gallery/core/network/internet_info.dart' as _i2;
import 'package:movies_gallery/features/movies_grid/data/data_source/movies_remote_DS.dart'
    as _i4;
import 'package:movies_gallery/features/movies_grid/data/models/movies_model.dart'
    as _i5;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [InternetInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockInternetInfo extends _i1.Mock implements _i2.InternetInfo {
  MockInternetInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> get isConnect =>
      (super.noSuchMethod(Invocation.getter(#isConnect),
          returnValue: Future.value(false)) as _i3.Future<bool>);
}

/// A class which mocks [RemoteDS].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteDS extends _i1.Mock implements _i4.RemoteDS {
  MockRemoteDS() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i5.MovieModel>> fetchMovies() =>
      (super.noSuchMethod(Invocation.method(#fetchMovies, []),
              returnValue: Future.value(<_i5.MovieModel>[]))
          as _i3.Future<List<_i5.MovieModel>>);
}
